@startuml
@startuml
title 登录用例的顺序图
actor user
user -> 登录界面: 输入用户名和密码
登录界面 ->数据库:查询用户名密码是否正确
alt 用户名密码正确
    数据库->user:以学生身份登录跳转到学生信息界面，以老师身份登录跳转到学生成绩列表界面
else 用户名或密码错误
    数据库->登录界面:提示用户名或密码错误
end
@enduml