@startuml
title 修改密码的顺序图
actor user
user -> 修改密码界面: 输入用户名和原密码和新密码
修改密码界面 ->数据库:查询用户名原密码是否正确
alt 用户名原密码正确且新密码与原密码不相同
    数据库->登录界面:完成修改，跳转到登录界面
else 用户名或密码错误或新密码与原密码相同
    数据库->修改密码界面:提示用户名或密码错误或与原密码相同，请重新输入
end
@enduml